export const animationTypes = {
  point: [
    { value: "fadeIn", label: "Fade In" },
    { value: "fadeOut", label: "Fade Out" },
    { value: "pulse", label: "Pulse" },
    { value: "bounce", label: "Bounce" },
    { value: "spin", label: "Spin" },
    { value: "grow", label: "Grow" },
    { value: "glow", label: "Glow" },
    { value: "glowPulse", label: "Glow Pulse" },
    { value: "electricFlicker", label: "Electric Flicker" },
    { value: "heatHaze", label: "Heat Haze" },
    { value: "scanline", label: "Scanline Sweep" },
    { value: "noiseDissolve", label: "Noise Dissolve" },
    { value: "ghostTrail", label: "Ghost Trail" },
    { value: "breathe", label: "Breathe" },
    { value: "pixelate", label: "Pixelate" },
    { value: "timeGradient", label: "Time Gradient" },
    { value: "prismShift", label: "Prism Shift" }
  ],
  polyline: [
    { value: "draw", label: "Draw Line" },
    { value: "drawReverse", label: "Draw Line (Reverse)" },
    { value: "fadeIn", label: "Fade In" },
    { value: "fadeOut", label: "Fade Out" },
    { value: "neonTrail", label: "Neon Trail" },
    { value: "glow", label: "Glow" },
    { value: "glowPulse", label: "Glow Pulse" },
    { value: "electricFlicker", label: "Electric Flicker" },
    { value: "heatHaze", label: "Heat Haze" },
    { value: "scanline", label: "Scanline Sweep" },
    { value: "sparkEmit", label: "Spark Emit" },
    { value: "weldTrail", label: "Weld Trail" },
    { value: "flightRoute", label: "Plane Takeoff/Land" },
    { value: "flightRouteCartoon", label: "Plane Takeoff/Land (Cartoon)" },
    { value: "waypointRoute", label: "Waypoint Stops (A-B-C)" },
    { value: "waypointRouteCartoon", label: "Waypoint Stops (Cartoon)" },
    { value: "arrowMarch", label: "Arrow March" },
    { value: "barrageOfArrows", label: "Barrage of Arrows" },
    { value: "jitterSketch", label: "Jitter Sketch" },
    { value: "noiseDissolve", label: "Noise Dissolve" },
    { value: "ghostTrail", label: "Ghost Trail" },
    { value: "breathe", label: "Breathe" },
    { value: "pixelate", label: "Pixelate" },
    { value: "timeGradient", label: "Time Gradient" },
    { value: "prismShift", label: "Prism Shift" }
  ],
  polygon: [
    { value: "fadeIn", label: "Fade In" },
    { value: "fadeOut", label: "Fade Out" },
    { value: "fill", label: "Fill Animation" },
    { value: "pulse", label: "Pulse" },
    { value: "glow", label: "Glow" },
    { value: "glowPulse", label: "Glow Pulse" },
    { value: "electricFlicker", label: "Electric Flicker" },
    { value: "heatHaze", label: "Heat Haze" },
    { value: "scanline", label: "Scanline Sweep" },
    { value: "jitterSketch", label: "Jitter Sketch" },
    { value: "noiseDissolve", label: "Noise Dissolve" },
    { value: "ghostTrail", label: "Ghost Trail" },
    { value: "breathe", label: "Breathe" },
    { value: "pixelate", label: "Pixelate" },
    { value: "timeGradient", label: "Time Gradient" },
    { value: "prismShift", label: "Prism Shift" }
  ],
  text: [
    { value: "fadeIn", label: "Fade In" },
    { value: "fadeOut", label: "Fade Out" },
    { value: "typewriter", label: "Typewriter" },
    { value: "bounce", label: "Bounce" },
    { value: "glow", label: "Glow" },
    { value: "glowPulse", label: "Glow Pulse" },
    { value: "electricFlicker", label: "Electric Flicker" },
    { value: "heatHaze", label: "Heat Haze" },
    { value: "scanline", label: "Scanline Sweep" },
    { value: "noiseDissolve", label: "Noise Dissolve" },
    { value: "ghostTrail", label: "Ghost Trail" },
    { value: "breathe", label: "Breathe" },
    { value: "pixelate", label: "Pixelate" },
    { value: "timeGradient", label: "Time Gradient" },
    { value: "prismShift", label: "Prism Shift" }
  ],
  feature: [
    { value: "field", label: "Field Animation" }
  ]
} as const;

export const clipColors = [
  "clip-color-1",
  "clip-color-2",
  "clip-color-3",
  "clip-color-4",
  "clip-color-5",
  "clip-color-6"
];
